services:
  db_dev:
    image: postgres:13.5
    restart: always
    ports:
      - "127.0.0.1:5444:5444"
    environment:
      - POSTGRES_PASSWORD=20052020
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=test
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: