services:
  db_dev:
    image: postgres:13.5
    restart: always
    ports:
      - "127.0.0.1:5444:5444"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=test
    volumes:
      - postgres:/var/lib/postgresql/data

  app_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - db_dev
    volumes:
      - ./src:/app/src

volumes:
  postgres: